apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dotnet-example-deployment
  labels:
    app: kubernetes-dotnet-example
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dotnet-example
      environment: production
  template:
    metadata:
      labels:
        app: kubernetes-dotnet-example
        environment: production
    spec:
      containers:
      - name: kubernetes-dotnet-example
        image: cdemi/kubernetes-dotnet-example:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
