apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dotnet-example-deployment
  labels:
    app: kubernetes-dotnet-example
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dotnet-example
      environment: production
  template:
    metadata:
      labels:
        app: kubernetes-dotnet-example
        environment: production
    spec:
      containers:
      - name: kubernetes-dotnet-example
        image: cdemi/kubernetes-dotnet-example:latest
        readinessProbe:
          httpGet:
            path: /health
            port: 8069
            scheme: HTTP
          periodSeconds: 1
          failureThreshold: 1
        env:
          - name: ASPNETCORE_URLS
            value: 'http://*:8069'
        ports:
          - containerPort: 8069
