apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dotnet-example-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dotnet-example-service
          servicePort: 8069